### ISSUE TITLE
Cannot capture Steam game

### ISSUE THREAD

**Issue by pmartiner** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#1]
Hi!
First of all, thank you for porting this awesome plugin for the OBS flatpak app :)
I've been trying to testing it on my current system, but it seems that the layer is not allowed to capture my game. I suspect it's due to my games not coming from flatpak apps (lutris, heroic game launcher, Arch Linux's Steam, etc.)
What can I do to fix this?

Hardware info:
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.15.12-arch1-1
Desktop:         GNOME
Display Server:  wayland

Thanks!

**Comment by pmartiner** [comment]
I fixed it by also installing the `obs-capture` plugin directly from the AUR

**Comment by SuNNjek** [comment]
Yes, the Vulkan layer only works for flatpaks, for non-flatpak applications the tools must be installed without flatpak.

If you want to build the AUR package without the plugin, a quick workaround would be to clone the AUR repo, remove the OBS dependency and add `-DBUILD_PLUGIN=off` to the build arguments. Then you can build it locally with `makepkg -scif`. Maybe I'll make another PR for separating the tools on the main repo when I find the time
