### ISSUE TITLE
Binary not available in steam sandbox

### ISSUE THREAD

**Issue by daynashaw** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#13]
Fedora Silverblue 36
Flatpak steam, flatpak OBS, flatpak OBSCkCapture

I have both org.freedesktop.Platform.VulkanLayer.OBSVkCapture and com.obsproject.Studio.Plugin.OBSVkCapture installed

obs-gamecapture %command%
Fails to launch on any game. (Vulkan, OpenGL / Native, Proton)

env OBS_VKCAPTURE=1 %command% / OBS_VKCAPTURE=1 %command%
Also does not work. The game launches, however OBS does not detect any windows available for capture.

flatpak run --command=sh com.valvesoftware.Steam
[📦 com.valvesoftware.Steam ~]$ obs-gamecapture
sh: obs-gamecapture: command not found

I have also tried manually searching for the binary in the steam sandbox but can't find anything. Maybe it is because steam just updated to freedesktop 22.08 and this extension is still on 21.08? I don't know what is wrong, but it is behaving as if the extension is actually not installed. 

Thanks.

**Comment by SuNNjek** [comment]
> Maybe it is because steam just updated to freedesktop 22.08 and this extension is still on 21.08?

Yeah, that's the reason. I didn't know it had updated, thanks for letting me know. I added a branch for 22.08 that will be published in a few hours. You might have to install that version manually after it is published.

**Comment by daynashaw** [comment]
Much love <3

**Comment by SuNNjek** [comment]
Build is published and works on my end. You just need to install the 22.08 branch by running `flatpak install org.freedesktop.Platform.VulkanLayer.OBSVkCapture` and selecting the correct branch.

**Comment by daynashaw** [comment]
ur so cool. Thank you a million. :)

Now to get the vkBasalt maintainer to do the same. Have a good weekend. :)

**Comment by jarrard** [comment]
> Build is published and works on my end. You just need to install the 22.08 branch by running `flatpak install org.freedesktop.Platform.VulkanLayer.OBSVkCapture` and selecting the correct branch.

Cool I'll give this a go. I also sometimes get a option called Stable but I'll select 22.08.
