### ISSUE TITLE
Feature/Documentation request: Use outside of steam

### ISSUE THREAD

**Issue by ljmc2000** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#2]
Is there a way to use this in applications outside of steam? org.polymc.PolyMC for example?

**Comment by SuNNjek** [comment]
Sure. If it's a vulkan application, the easiest way would be to set the environment variable, this can be done like this:
```
flatpak override --env=OBS_VKCAPTURE=1 <app-id>
```

If it's an OpenGL application, it might be a little trickier. I assume PolyMC is Minecraft related, which I think uses OpenGL. In that  case you could try the following:
```
flatpak run --command=obs-glcapture org.polymc.PolyMC polymc
```

Let me know if the above worked for you (or not :sweat_smile:)
I'll try to update the README later when I have more time

**Comment by ljmc2000** [comment]
bwrap: execvp obs-glcapture: No such file or directory

To be clear, it's a launcher, like steam, and like steam you can adjust command parameters. Outside of flatpak, it does work if you set "wrapper command" to obs-glcapture.

I think it might not be using the opengl runtime and I'm guessing that's what triggers whatever rule makes it visible in steam? So is there a way to trigger that rule manually?

**Comment by SuNNjek** [comment]
Ok, if you can modify the launch parameters, then you should be able to just do the same as you would without flatpak.
Also I just realized it should probably be
```
flatpak run --command=/usr/lib/extensions/vulkan/OBSVkCapture/bin/obs-glcapture org.polymc.PolyMC polymc
```

Could you clarify what you mean by "rule"?

**Comment by ljmc2000** [comment]
flatpak run --command=/usr/lib/extensions/vulkan/OBSVkCapture/bin/obs-glcapture org.polymc.PolyMC polymc
bwrap: execvp /usr/lib/extensions/vulkan/OBSVkCapture/bin/obs-glcapture: No such file or directory

As for what I mean by rule, I'm guessing there's some bit of code which means "if application uses opengl or vulkan, then provide obs-vkcapture and obs-glcapture

**Comment by SuNNjek** [comment]
Unfortunately, no such "rule" exists as of now.

As for your problem, it looks like PolyMC isn't actually based on the Freedesktop 21.08 platform, but instead on the KDE 5.15 platform. This would explain why it's not working. The vulkan layer is an extension to the Freedesktop platform so it doesn't show up on apps based on the KDE platform. That means the PolyMC flatpak won't work with this extension right now

I don't know if I could even get support in for pure KDE platforms. I'll take a look at it later, though I can't promise that it's gonna work. I suppose the best solution to this problem would be if the PolyMC flatpak migrated to the KDE 5.15-21.08 platform, this should make it show up.

**Comment by ljmc2000** [comment]
https://docs.flatpak.org/en/latest/tips-and-tricks.html#testing-an-app-with-a-different-runtime

Don't suppose something like that would work?

**Comment by SuNNjek** [comment]
That looks interesting, might just work. It should be
```
flatpak run --runtime=org.kde.Platform --runtime-version=5.15-21.08 org.polymc.PolyMC
```
Then add `obs-glcapture` as the wrapper command

In the meantime I also tried compiling the PolyMC flatpak with the 5.15-21.08 runtime, which works and the commands show up in the flatpak filesystem. Unfortunately I don't get any image in my OBS when running Minecraft through it. I don't know if Minecraft even works with this plugin to be honest. The OpenGL capture seems to be hit and miss, some applications work, some don't :cry:

**Comment by ljmc2000** [comment]
![Screenshot_20220204_110527](https://user-images.githubusercontent.com/14955891/152518650-b24ebedf-a617-4405-b97b-6960b341a58b.png)

Had to set the wrapper command to /lib/extensions/vulkan/OBSVkCapture/bin/obs-glcapture  
it was not detected in $PATH  
but it works so there's that

**Comment by SuNNjek** [comment]
Nice
Weird that it's not in $PATH though, gonna have to look into that

**Comment by SuNNjek** [comment]
>note: system obs not flatpak obs in picture

Does that mean it doesn't work with flatpak OBS or have you just not tried that?

**Comment by ljmc2000** [comment]
Just haven't tried. Flatpak OBS seems to be borked on my system at the moment.

**Comment by ljmc2000** [comment]
![Screenshot_20220205_165622](https://user-images.githubusercontent.com/14955891/152650954-35c6526c-e3d6-4cd9-896a-3dbb2bc2e277.png)

Okay, apparantly a quite a few packages are borked under flatpak at the moment and OBS is one of them, but someone found a workaround so here's minecraft in OBS flatpaked edition

**Comment by ljmc2000** [comment]
> That looks interesting, might just work. It should be
> 
> ```
> flatpak run --runtime=org.kde.Platform --runtime-version=5.15-21.08 org.polymc.PolyMC
> ```

This seems to have solved it anyway, so I'm closing the issue. Thanks for your help.
