### ISSUE TITLE
Doesn't work with Steam Flatpak

### ISSUE THREAD

**Issue by Grafcube** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#43]
The only versions I see available on Flathub are 21.08 and 22.08, while Steam appears to be using `org.freedesktop.Platform/x86_64/23.08`. I'm not sure when Steam started using this runtime and I installed vkcapture for the first time today, but none of the games start if I use `obs-gamecapture` in the launch options and setting the environment variable doesn't work either.

**Comment by SuNNjek** [comment]
Thanks for the heads up.
You're correct, this flatpak isn't built for the new runtime yet, I'll take a look at it later.
