### ISSUE TITLE
How exactly do I capture a Steam game?

### ISSUE THREAD

**Issue by kozross** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#8]
I have both this package and Steam installed via Flatpak. What exact steps do I need to take to capture a Steam game?

**Comment by SuNNjek** [comment]
See https://github.com/nowrep/obs-vkcapture#usage

**Comment by kozross** [comment]
That tells me basically nothing. Do I need to start Steam using that command? Do I need to set launch options for the game using that command? Some other thing?

**Comment by ThomChroma** [comment]
Add this environment variable `OBS_VKCAPTURE=1 %command%` to the game launch options.

**Comment by SuNNjek** [comment]
Closing this since it's already documented in the main repo's Readme
