### ISSUE TITLE
Issues with certain software, update freedeskop.platform to 24.08 is the solution?

### ISSUE THREAD

**Issue by Flax4** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#86]
I love using VkCapture for streaming, but recently when using Bottles the option is greyed out to toggle it, even though I have the Flatpaks installed. I noticed that bottles has updated to 24.08, could that be the reason VkCapture is not working?

com.obsproject.Studio.Plugin.OBSVkCapture 1.5.0
org.freedesktop.Platform.VulkanLayer.OBSVkCapture 1.5.0 - 23.08

are installed.

![1](https://github.com/user-attachments/assets/7864996f-fb24-485a-bc0f-bc46fb3cd31d)

**Comment by SuNNjek** [comment]
Yes, this will most likely be the reason. I'll try and get a 24.08 build up soon

**Comment by SuNNjek** [comment]
@Flax4 There should now be 24.08 version, can you install it and check again?

**Comment by Flax4** [comment]
It's working perfectly now, thanks for the update!
